#!/usr/bin/env sh

[ "$1" = "restore" ] && swaybg -i "$HOME/.config/wallpaper"

WALLPAPER_DIRECTORY="$HOME/wallpapers"
#SELECTED_WALLPAPER=$(ls "$WALLPAPER_DIRECTORY/*" | fzf --preview='kitty icat --clear --transfer-mode=memory --stdin=no --place="${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0" {}' --tac)

SELECTED_WALLPAPER=$(find "$WALLPAPER_DIRECTORY" -type f |
    fzf --preview='kitty icat --clear --transfer-mode=memory --stdin=no {}' --tac)
rm "$HOME/.config/wallpaper"
ln -s "$SELECTED_WALLPAPER" "$HOME/.config/wallpaper"

pkill -f swaybg
swaybg -i "$HOME/.config/wallpaper" &
# ls ~/wallpapers/* | fzf --preview='kitty icat --clear --transfer-mode=memory --stdin=no --place="${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0" {}' --tac | xargs -r swaybg -i
